### ISSUE TITLE
any coding for measuring specific class

### ISSUE THREAD

**Issue by WiselyC0430** [wkcn/TinyViT#1]
i came across a issue that i cannot loading the self-trainned model in inference.py. also i cannot evaluate each classification class and show each accuracy. any suggestions?

**Comment by wkcn** [comment]
Hi @WiselyC0430 , thanks for your attention to our work!

Is the result correct when running `main.py` to evaluate the model?
I do not have the code to measure specific class. You can change the validation function in https://github.com/wkcn/TinyViT/blob/main/main.py#L428.
